branch-defaults:
  default:
    environment: django-env
    group_suffix: null
  main:
    environment: django-env
    group_suffix: null
environment-defaults:
  django-env:
    branch: null
    repository: null
global:
  application_name: django-tutorial
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.9
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
